import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ContainerComponent from "@/components/container/Container";
import headerTabs from "@/components/Header/HeaderLinks/headerLinks";
import HeaderComponent from "@/components/Header/MainHeader/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContainerComponent size="large">
          <HeaderComponent tabs={headerTabs} />
        </ContainerComponent>
        <ContainerComponent size="medium">{children}</ContainerComponent>
      </body>
    </html>
  );
}
