import type { Metadata } from "next";
import { Work_Sans, Roboto } from "next/font/google";
import "./globals.css";
import ContainerComponent from "@/components/container/Container";
import headerTabs from "@/components/Header/HeaderLinks/headerLinks";
import HeaderComponent from "@/components/Header/MainHeader/Header";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${roboto.variable} antialiased`}>
        <ContainerComponent size="large">
          <HeaderComponent tabs={headerTabs} />
        </ContainerComponent>
        <ContainerComponent size="medium">{children}</ContainerComponent>
      </body>
    </html>
  );
}
